# Generated by Django 3.0.6 on 2020-05-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamreal',
            name='last_name',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
